### ISSUE TITLE
error attaching volume in cloudstack deploy

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/fogbow-manager#313]
@fubica reported he is facing some problemas attaching volumes into REC cloudstack deployment. It seems the volume starts as **allocated** instead as **available**. Also, it is only  possible to remove the volume after a while. The problem appears non-deterministically. 

We should try to reproduce it (and/or check the 27/oct/2016 log)

**Comment by fubica** [comment]
On Oct 27, 2016, at 10:21 , Thiago Emmanuel Pereira <notifications@github.com> wrote:

> @fubica reported he is facing some problemas attaching volumes into REC cloudstack deployment. It seems the volume starts as allocated instead as available. Also, it is only possible to remove the volume after a while. The problem appears non-deterministically.
> 
it seems to be more complex. it starts as allocated, then it goes to ready (after quite some time). however, even after it transits to ready, i still could not attach the volume. strangely (or maybe not), when i sshed to the instance that i had tried to attach the volume, the device had been created (i could not tell when, since i tried several times to attach the device with no luck).

> We should try to reproduce it (and/or check the 27/oct/2016 log)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________
 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br
